### ISSUE TITLE
Memory provider: support `optionsFilter` in facet

### ISSUE THREAD

**Issue by michsa** [futil-js/contexture-core#39]
Now that we're using memory provider in our contexture-react storybook, we should probably support this. Our React component has a search bar for the visible options that sets the `optionsFilter` property on the node; the provider should use this in its `result` function to filter the returned options: https://github.com/smartprocure/contexture/blob/ef8453220d028658eaf1dfb82218b4d80492b69d/src/provider-memory/exampleTypes.js#L47

(Note that #37 modifies the same code, so probably best to hold off on this until that PR is updated and merged)

**Comment by daedalus28** [comment]
Fixed by #42
