### ISSUE TITLE
Memory provider bugs

### ISSUE THREAD

**Issue by Akrion** [futil-js/contexture-core#47]
Few things I noticed when trying to play with the memory provider.

- [x]  `Facet` type `exclude` filter option does not work
- [x]  `Exists` type does not work on the initial load. Have to set a value and reset to the value you want for it to work.
- [ ] `Add Custom Filter` button shows on the filters side when there are no filters not already used. It should not show when all filters have been already used.
- [x]  `Date` type
   - [x] The `rolling` option does not work
   - [x] The whole thing does not work with string dates. Have to convert the date to `ms` with `getTime()` 

These might also be issues with the provider itself. Opening it here to start keeping track.

**Comment by stellarhoof** [comment]
All these items have been addressed.
